"""add irrigation_type, water_source, mulching_used, region to farms

Revision ID: 172b04f2eeca
Revises: c7703534334f
Create Date: 2026-08-16 10:28:22.487173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172b04f2eeca'
down_revision: Union[str, Sequence[str], None] = 'c7703534334f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('irrigation_type', sa.String(length=50), server_default='Rainfed', nullable=False))
    op.add_column('farms', sa.Column('water_source', sa.String(length=50), server_default='Rainwater', nullable=False))
    op.add_column('farms', sa.Column('mulching_used', sa.String(length=5), server_default='No', nullable=False))
    op.add_column('farms', sa.Column('region', sa.String(length=50), server_default='South', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'region')
    op.drop_column('farms', 'mulching_used')
    op.drop_column('farms', 'water_source')
    op.drop_column('farms', 'irrigation_type')
    # ### end Alembic commands ###
