"""remove village district state from users

Revision ID: 585a88f4c5e3
Revises: 202301da4cdf
Create Date: 2026-08-02 12:16:01.111877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585a88f4c5e3'
down_revision: Union[str, Sequence[str], None] = '202301da4cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'village')
    op.drop_column('users', 'district')
    op.drop_column('users', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('village', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
