"""add crop_growth_stage to farms

Revision ID: c7703534334f
Revises: e211de0dbe9b
Create Date: 2026-08-16 00:04:23.700230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7703534334f'
down_revision: Union[str, Sequence[str], None] = 'e211de0dbe9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('crop_growth_stage', sa.String(length=50), server_default='Sowing', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'crop_growth_stage')
    # ### end Alembic commands ###
