"""add crop_type to farms

Revision ID: e211de0dbe9b
Revises: 7ba5785467fc
Create Date: 2026-08-03 13:55:20.315528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e211de0dbe9b'
down_revision: Union[str, Sequence[str], None] = '7ba5785467fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('crop_type', sa.String(length=100), server_default='unspecified', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'crop_type')
    # ### end Alembic commands ###
